server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
security:
  jwt:
    secret-key: cybertek
springdoc:
  swagger-ui:
    path: /swagger-ui.html